src/commandline.coffee
The help message of noconfig flag currently states that only the `COFFEELINT_CONFIG` environment variable is being ignored.
But looking at:
https://github.com/clutchski/coffeelint/blob/48cd906b4b403cc7e949fe5e630a89dd413c6ba6/src/commandline.coffee#L65
https://github.com/clutchski/coffeelint/blob/48cd906b4b403cc7e949fe5e630a89dd413c6ba6/src/commandline.coffee#L190
It seems that it completely ignores all config files.
This lead to some confusion in a change to phabricator: https://secure.phabricator.com/D11196
=> improve help message for noconfig option

src/coffeelint.coffee, src/rules/braces_spacing.coffee, test/test_braces_spacing.coffee
currently implement as a plugin at [charlierudolph/coffeelint-braces-padding](https://github.com/charlierudolph/coffeelint-braces-padding) but thought this is something that should be included in the core. Would be very easy to extend this for `brackets_padding` and `parens_padding`
=> braces_padding

src/lexical_linter.coffee, src/rules/no_implicit_braces.coffee, src/rules/no_implicit_parens.coffee, test/test_no_implicit_braces.coffee
This was caused because class declarations generate a brace so this
changes it to ignore the first implied brace, but take into account any
future implied braces
Fixes #324
Renamed test_braces.coffee to test_no_implicit_braces.coffee
=> Fix no_implicit_braces error in class declarations

src/coffeelint.coffee
I'm preparing to submit a PR to [linter-coffeelint](https://github.com/AtomLinter/linter-coffeelint) to get it to require CoffeeLint directly instead of calling the CLI and regexing the values out of that output. Atom has a `window` variable, so the current behavior assumes that it's in a browser and that node isn't available.
=> Work around a require issue with atom

src/rules/arrow_spacing.coffee, test/test_arrows.coffee
Perhaps there is a good reason that this was left out, but I definitely want the same spacing enforced for my arrows and fat arrows. Thoughts?
=> Add fat arrow to arrow_spacing

src/rules/max_line_length.coffee
While `String.prototype.trim` is part of the ES spec, `trimRight` and `trimLeft` aren't.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/TrimRight
This improves compatibly running the `MaxLineLength` linter in browsers that may not support `trimRight`.
=> Avoid non-standard String.prototype.trimRight

index-bottom.html, index.html
overcommit is a fully configurable and extendable Git hook manager that
includes out-of-the-box support for CoffeeLint.
=> Add link to overcommit

src/rules/no_interpolation_in_single_quotes.coffee, test/test_no_interpolation_in_single_quotes.coffee
This changes no_interpolation_in_single_quotes so it will now look to
see that the string is actually single-quoted.
Closes #398
=> Fix no_interpolation_in_single_quotes to only handle single quotes

package.json, src/commandline.coffee, src/configfinder.coffee
This allows comments to happily exist in the config file. It's nice to allow teams to explain their rules or whatever else they need.
=> Strip comments from config file before parsing

src/rules/missing_fat_arrows.coffee
This particular line was throwing a reference error on invoking the missing fat arrows rule. The reason is that not all node.variable have a base property (another way to be to call @isCode, but perhaps this is faster?).
=> Fix for issue #412

src/rules/spacing_after_comma.coffee, test/test_spacing_after_comma.coffee
=> spacing_after_comma: Ignore comma in generated REGEXP calls.

coffeelint.json, src/coffeelint.coffee, src/commandline.coffee, src/htmldoc.coffee, src/reporters/checkstyle.coffee, src/reporters/csv.coffee, src/reporters/default.coffee, src/reporters/jslint.coffee, src/reporters/raw.coffee, src/ruleLoader.coffee, src/rules/no_debugger.coffee, test/test_debugger.coffee
For backward compatibility this does not warn about `console` calls by default
How to enable in your coffeelint.json
"no_debugger": {
"level": "error",
"console": true
},
How to allow a console call:
```CoffeeScript
console.log(whatever)
```
Fixes #416 
Fixes #411
=> Add an option to no_debugger to catch console calls

src/rules/newlines_after_classes.coffee
This documents the `value` option for the `newlines_after_classes` rule – I had no idea it was configurable till I looked at the source.
Refs https://github.com/atom/atom/pull/6898#discussion_r30926627
=> Document newlines_after_classes config option

src/rules/arrow_spacing.coffee, test/test_arrow_spacing.coffee
This fixes a crash if an arrow is the very beginning of a file, thus
having no previous tokens.
Fixes #481
=> arrow_spacing: fixes crash at beginning of line

src/commandline.coffee, test/fixtures/custom_extention/clean.csbx, test/test_commandline.coffee
Add '--ext' CLI option to include additional file extension, fe
`$coffeelint --ext csbx ./testdir/`
will check '.coffee' and '.csbx' files.
Extension may be listed by comma
`$coffeelint --ext csbx,myext,myext2 ./testdir/`
Why - we are use custom CoffeeScript file extention '.csbx' - its coffee with React inserts in backtricks and custom builder for result js file. Extention used as flag for different processors and save a lot of time, excluding unnecessary React processor step for pure coffee files. 
So, we are need custom filenames in `coffeelint`
=> Add --ext CLI option to include additional file extension

src/coffeelint.coffee, src/rules/no_private_function_fat_arrows.coffee, test/test_no_private_function_fat_arrows.coffee
I set it to warn, because this is clearly a mistake. We could also even make it an error.
This makes linting complain aobut:
```coffee
class Foo
foo = =>
```
It should be:
```coffee
class Foo
foo = ->
```
And CoffeeScript produces the same code in both cases.
=> Added no_private_function_fat_arrows rule

src/rules/ensure_comprehensions.coffee, test/test_ensure_comprehensions.coffee
This fixes the linter seeing an equal sign inside of a nested loop.
Normally the linter checks for an '=' to determine if the for loop is a
possible comprehension. This also picked up an equal sign inside of a
nested loop.
This fixes the linter seeing an euqal sign inside of a nested loop by
checking the number of parens ('(' or ')') and only triggering the rule
if there is a balanced number of parens.
Fixes #486
=> Ignore '=' in non-comprehension nested-for-loops

src/rules/braces_spacing.coffee, test/test_braces_spacing.coffee
This fixes problems where a generated token interferes with the check to
make sure the token after the brace token ('{' or '}') is on the same
line. If it is a generated token, then it means that the user did not
actually type in that token.
Fixes #489
=> braces_spacing: ignore generated tokens on same line

src/lexical_linter.coffee, src/line_linter.coffee, src/rules/missing_fat_arrows.coffee, src/rules/newlines_after_classes.coffee, src/rules/no_backticks.coffee
Fixes some typos, extra spaces and...
1. lexical_linter rules can now return custom line numbers.
2. line_linter now returns a proper `line` property (was always null before)
=> Small api fixes

src/rules/indentation.coffee, test/test_indentation.coffee, test/test_no_nested_string_interpolation.coffee
This addresses several issues regarding indentation.
1. Being able to indent conditional if/else assignments to make them
look more pleasing.
Most users wanted to do something like this
```cs
y = if a
true
else
false
```
This now won't return an error for the user.
Fixes #468
Fixes #345
_2. Fixed some bugs around chaining (.) operations
There were some cases of chaining operators not being evaluated
correctly. One was due to not checking for end tokens with `newLine`
properties.
Fixes #469
Fixes #348
_3. Better cleanup of indented multi-line conditional statements.
Just some cleanup of the logic for the conditional in an if statement.
_4. Empty if conditionals now do not generate indent message
While I think more often than not you should never need to have an empty
if conditional in your …
=> Fix several issues related to indentation

src/rules/newlines_after_classes.coffee, test/test_newlines_after_classes.coffee
newline_after_classes has been rewritten to use the lexical linter
rather than the line linter. The previously written code did not catch a
lot of the extra cases caused by CoffeeScript's tokenizer/lexer.
This should now be much more accurate, this will now ignore classes
scoped within other classes (will just be generally ignored)
Fixes #230
Fixes #245
Fixes #347
Fixes #375
=> newlines_after_classes: rewritten to make it work

src/rules/no_stand_alone_at.coffee, src/rules/no_this.coffee, test/test_no_this.coffee
If `no_stand_alone_at` is set to warn or error, then it will suppress
any errors that come from this rule when the code uses a singular
`this`. It will continue checking this rule for non stand-alone this.
Fixes #464
=> no_this: make compatible with no_stand_alone_at

src/ast_linter.coffee, src/rules/missing_fat_arrows.coffee, test/test_missing_fat_arrows.coffee
Prototypes are no longer requirement to use a fat arrow.
```coffeescript
SuperHero::getPower = ->
@power
```
This will now not return an error.
Fixes #296
=> missing_fat_arrows: remove requirement for prototypes

src/rules/arrow_spacing.coffee, test/test_arrow_spacing.coffee
This fixes #304 (and generalises #173, and obsoletes #148).
I basically removed the guard in #173 so now any empty function is ignored by the rule. #148 was ignoring empty functions only at the end of files, which is no longer necessary because those are a subset of the new behaviour.
It passes all the tests, but there's a possibility that the existing empty function behaviour was restricted for a reason that I don't understand. Feedback welcome!
=> arrow_spacing: empty functions redux

src/rules/missing_fat_arrows.coffee
Removed fat arrow that was introduced in
30e28a6f362abadd3aa450bb7e0402060d909d29
=> missing_fat_arrows: remove unnecessary fat arrow

src/rules/indentation.coffee, test/test_indentation.coffee
This fixes problems with chaining identifying separate code blocks as
the same chain.
This also reverts where we ignored the slightly off alignment that we
allowed from #348.
See issue #504.
=> indent: fix chaining problems caused by regression

src/rules/indentation.coffee
This removes the isInterpIndent check in the indent rule. It seems that
since the fixes made in CoffeeScript 1.9.x, this check is no longer
needed.
=> indent: remove isInterpIndent check

test/test_commandline.coffee
This changes the test for "minimal" config to do a deepEqual comparison
check between the config and the minimal output rather than doing a
string comparison which could be different due to how javascript orders
keys in the object.
=> test_commandline: use deepEqual for minimal JSON check

.npmignore
I've seen a few people think they can just go modifying this file to change the global/default configuration. I think it's best to just not package it on npm.
=> npmignore coffeelint.json

coffeelint.json, src/coffeelint.coffee, src/rules/spacing_after_comma.coffee, test/test_spacing_after_comma.coffee
Adding the rule, `spacing_after_comma` for coffeelint development.
Also removed unnecessary check for isObject in test
=> spacing_after_comma: enable this for development

src/commandline.coffee, src/configfinder.coffee
I think it makes more sense to move this than to re-implement it over in [linter-coffeelint](https://github.com/AtomLinter/linter-coffeelint/issues/51#issuecomment-151946844)
=> Move $COFFEELINT_CONFIG into configfinder

src/coffeelint.coffee, src/line_linter.coffee, test/test_comment_config.coffee
Closes #540 
Changes:
1. Changes the semantics of `coffeelint-enable`:
*From*: enables all rules that were previously disabled by a `coffeelint-disable` directive
*To*: resets the ruleset to whatever was originally specified in `coffeelint.json`
This is because the current implementation is buggy and mixes immutable with mutable structures. While there are ways around this, it makes the code needlessly complex and not that much useful.
Example of existing bug
```coffeescript
foo "bar"  # error
```
```coffeescript
foo "bar"  # no error
```
2. Adds the following directives that work like their parents but only for the current line
* `coffeelint-disable-line=foo,bar,baz`
* `coffeelint-enable-line=foo,bar,baz`
3. Overloads `coffeelint-disable` to disable all registered rules. Primary use …
=> Better directive handling

package.json, src/commandline.coffee
Upgrades [`node-ignore`](https://www.npmjs.com/package/ignore) to the latest `3.0.9` to solve several known issues, including:
- Files should not be re-included if the parent directory is ignored, [#10](https://github.com/kaelzhang/node-ignore/issues/10)
- Works for [windows](https://ci.appveyor.com/project/kaelzhang/node-ignore), finally. [#5](https://github.com/kaelzhang/node-ignore/issues/5)
- Better Handling with trailing whitespaces, wildcards of ignore patterns, according to [gitignore spec](https://git-scm.com/docs/gitignore), and passed all cases described in the spec.
=> Upgrade node-ignore -> 3.x to solve several known issues.

src/coffeelint.coffee, test/test_literate.litcoffee
This PR adds support for trailing tab whitespace in literate files.
See #557 for more.
=> Support for tab indented literate files added

src/commandline.coffee, src/configfinder.coffee, src/ruleLoader.coffee
[A couple](https://github.com/bsklaroff/coffeelint-camel-case-vars) of older [custom rules](https://github.com/begizi/coffeelint-limit-newlines) written for coffeelint are written in coffeescript and are not compiled to js prior to publishing to npm. While this is technically an issue with the modules themselves (especially when they advertise an inexistent `index.js` as an entry point), I see no reason coffeelint couldn't be more coffeescript friendly, given its scope.
This patch instructs `resolve` to also accept coffee and litcofee files and thus prevent issues like this:
```
Error: Cannot find module 'coffeelint-limit-newlines' from 'B:\node-luacheck\src'
at module.exports (B:\node-luacheck\node_modules\coffeelint\node_modules\resolve\lib\sync.js:32:11)
at expandModuleNames …
```
=> Allow direct loading of .coffee modules

package.json
Reduce the scope of https://github.com/clutchski/coffeelint/pull/573
Resolves security issues with old nested minimatch dependencies. Vows [still hasn't updated to a newer minimatch](https://github.com/vowsjs/vows/issues/370) but it is a development dependency so that shouldn't cause any issues.
=> update glob and browserify to fix minimatch security issues

index-bottom.html, index.html
=> Fix misleading information about plugins API

.travis.yml, Cakefile, package.json, src/cache.coffee, src/coffeelint.coffee, src/commandline.coffee, src/reporters/passthrough.coffee, src/rules/no_backticks.coffee, src/rules/no_implicit_braces.coffee, src/rules/no_implicit_parens.coffee, src/rules/prefer_english_operator.coffee, src/rules/space_operators.coffee, test/fixtures/custom_rules/voldemort.coffee, test/fixtures/mock_node_modules/he_who_must_not_be_named/he_who_must_not_be_named.coffee, test/fixtures/mock_node_modules/he_who_must_not_be_named/index.js, test/test_commandline.coffee, test/test_missing_fat_arrows.coffee, test/test_no_backticks.coffee, test/test_no_implicit_braces.coffee, test/test_no_unnecessary_fat_arrows.coffee, test/test_reporters.coffee, test/test_space_operators.coffee, vowsrunner.js
Still 3 broken tests, 1 test is due to possibly to bug described here: jashkenas/coffeescript#4463
=> Fixes to support CS2

test/test_indentation.coffee
This test shows a bug introduced in 1.16.1 (not existent in 1.16.0). Only seems to happen based on using the `prop` function in some instances:
```coffeescript
$('<input>')
.prop('placeholder', $el.prop('placeholder'))
$('<input>')
.prop('placeholder', @$el.attr('placeholder'))
$('<input>')
.prop('placeholder', window.prop('placeholder'))
$('<input>')
.prop('placeholder', @$el.prop('placeholder'))
$("body")
.addClass("alpha--" + beta)
.addClass("charlie")
$("body")
.addClass("alpha--" + beta).addClass("charlie")
```
Both issues are regressions as they worked in 1.16.0. Not sure as to the fix, but there was a large refactor of the indentation in 1.16.1
=> Add failing tests for indentation lint bug

src/commandline.coffee
Why would anyone ever want to lint the contents of `node_modules`?
=> Always ignore node_modules
