clutchski/coffeelint

- .travis.yml
Making a PR to make sure this doesn't error out.
> Add node v0.12 and iojs to travis.yml file for testing.

- src/rules/missing_fat_arrows.coffee
- test/test_missing_fat_arrows.coffee
see https://github.com/clutchski/coffeelint/pull/391
> missing_fat_arrows: added strict-mode option, defaults to false

- src/rules/camel_case_classes.coffee
- test/test_identifier.coffee
lowerCamelCase vs UpperCamelCase, who really cares? Apparently I do. :innocent:
> pedantic, semantic alteration.

- src/rules/missing_fat_arrows.coffee
- test/test_missing_fat_arrows.coffee
> missing_fat_arrows: fix for #412

- src/rules/no_unnecessary_double_quotes.coffee
- test/test_no_unnecessary_double_quotes.coffee
> no_unnecessary_double_quotes: Ignore flags in generated RegExp calls

- src/rules/empty_constructor_needs_parens.coffee
- test/test_constructor_needs_parens.coffee
> empty_constructor_needs_parens: detect indexes

- src/coffeelint.coffee
- src/rules/no_this.coffee
- test/test_no_this.coffee
- test/test_prefer_english_operator.coffee
It does not really work. Why? :-(
> no_this rule

- src/rules/camel_case_classes.coffee
- test/test_identifier.coffee
> Allow private camel case classes

- src/coffeelint.coffee
- src/rules/eol_last.coffee
- test/test_eol_last.coffee
> A rule to require an empty line at the end of the file

- coffeelint.json
- src/coffeelint.coffee
- src/commandline.coffee
- src/configfinder.coffee
- test/test_commandline.coffee
Fixes #452
See https://gist.github.com/AsaAyers/c58e78104ccc0d5969b5 for why you should use this.
TODO
=====
> Add --trimconfig option and verify that coffeelint uses a minimal config

- src/rules/ensure_comprehensions.coffee
- test/test_ensure_comprehensions.coffee
Handles a list comprehension inside a function call
Fixes #465
> ensure_comprehensions: now handles comprehensions inside function calls

- src/rules/no_implicit_braces.coffee
- test/test_no_implicit_braces.coffee
This PR reworks no_implicit_braces to better handle edge cases
CoffeeScript generates implicit braces starting at the first instance
method of the class (aka, the prototypes of the Object), it is actually
not generating it for the Class persay. If there is code that is not
part of the prototype/instance methods of the class (akin to the class
methods/properties of the Object), then it throws off where the '{' is
generated.
Fixes #458, Fixes #459
> Reworked no_implicit_braces for non-standard cases

- src/rules/eol_last.coffee
- test/test_eol_last.coffee
> eol_last: error if file ends with multiple newlines

- .travis.yml
> Only install new npm if node is v0.8

- src/rules/newlines_after_classes.coffee
- test/test_newlines_after_classes.coffee
Fixes issues brought on from PR #495
Fixes #509
> newlines_after_classes: fix parsing for class ending

- src/rules/cyclomatic_complexity.coffee
- test/test_cyclomatic_complexity.coffee
> cyclomatic_complexity: ignore nested functions

- generated_coffeelint.json
- src/coffeelint.coffee
- src/rules/arrow_spacing.coffee
- src/rules/camel_case_classes.coffee
- src/rules/duplicate_key.coffee
- src/rules/empty_constructor_needs_parens.coffee
- src/rules/no_backticks.coffee
- src/rules/no_debugger.coffee
- src/rules/no_empty_param_list.coffee
- src/rules/no_interpolation_in_single_quotes.coffee
- src/rules/no_nested_string_interpolation.coffee
- src/rules/no_plusplus.coffee
- src/rules/no_throwing_strings.coffee
- src/rules/space_operators.coffee
- src/rules/spacing_after_comma.coffee
- test/fixtures/mock_node_modules/he_who_must_not_be_named/he_who_must_not_be_named.coffee
- test/test_commandline.coffee
- test/test_transform_messes_up_line_numbers.coffee
* Removing spacing from array brackets
* "default" coffeelint.json regenerated
> Final cleanup

- package.json
- src/reporters/checkstyle.coffee
This fixes double quotes problem for checkstyle
> Fix checkstyle

- src/rules/no_implicit_braces.coffee
- test/test_no_implicit_braces.coffee
Now checks class names for '.'
Closes #549
> Fix false positive with no_implicit_braces

- src/reporters/checkstyle.coffee
- src/reporters/csv.coffee
- src/reporters/default.coffee
- src/reporters/jslint.coffee
- src/reporters/raw.coffee
> Fix reporters printing warnings when quiet flag set

- src/rules/duplicate_key.coffee
- src/rules/empty_constructor_needs_parens.coffee
- src/rules/no_debugger.coffee
- src/rules/no_implicit_braces.coffee
- src/rules/no_stand_alone_at.coffee
- src/rules/no_unnecessary_fat_arrows.coffee
- src/rules/non_empty_constructor_needs_parens.coffee
- test/test_no_implicit_braces.coffee
- test/test_no_stand_alone_at.coffee
Updates for PR #567.
Running this to test with travis.
> Changes for PR #567 to pass latest master of CoffeeScript
